@echo off
REM ============================================================================
REM  Second Brain Kit — Windows Setup Script
REM ============================================================================
REM  This script:
REM    1. Checks Python availability
REM    2. Asks for Obsidian vault path
REM    3. Copies vault-template to the vault
REM    4. Installs Python dependencies
REM    5. Generates config.toml
REM    6. Prints post-install instructions
REM ============================================================================

setlocal enabledelayedexpansion
title Second Brain Kit Setup

echo =====================================================
echo  Second Brain Kit — Windows Setup
echo =====================================================
echo.

REM ---- Check Python ----
python --version >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Python is not installed or not in PATH.
    echo        Please install Python 3.11 or later from https://python.org
    pause
    exit /b 1
)

REM ---- Get vault path ----
set "VAULT_PATH="
set /p VAULT_PATH=Enter the full path to your Obsidian vault (e.g., D:\MyVault): 
if "%VAULT_PATH%"=="" (
    echo [ERROR] Vault path cannot be empty.
    pause
    exit /b 1
)

REM Normalise path (remove surrounding quotes if any)
set VAULT_PATH=%VAULT_PATH:"=%

if not exist "%VAULT_PATH%" (
    echo [ERROR] Path does not exist: %VAULT_PATH%
    echo        Please verify the path and re-run.
    pause
    exit /b 1
)

echo [OK] Vault found at: %VAULT_PATH%
echo.

REM ---- Install Python dependencies ----
echo [*] Installing Python dependencies...
python -m pip install portalocker --quiet
if %ERRORLEVEL% neq 0 (
    echo [WARN] pip install failed. You may need to install 'portalocker' manually.
)

REM ---- Copy vault-template ----
echo [*] Copying vault-template to your vault...
set "SCRIPT_DIR=%~dp0"

xcopy /E /I /Y "%SCRIPT_DIR%vault-template\*" "%VAULT_PATH%\" >nul
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Failed to copy template files.
    pause
    exit /b 1
)
echo [OK] Template files copied.

REM ---- Generate config.toml ----
set "CONFIG_FILE=%VAULT_PATH%\.second-brain-config.toml"

REM Check if config already exists
if exist "%CONFIG_FILE%" (
    echo [*] Config file already exists at %CONFIG_FILE%
    echo    Run setup again with '--force' to overwrite.
) else (
    echo [*] Writing config to %CONFIG_FILE%...

    > "%CONFIG_FILE%" (
        echo # Second Brain Kit — generated by setup.bat
        echo.
        echo [vault]
        echo path = "%VAULT_PATH:\=\\%"
        echo.
        echo [supervisor]
        echo enabled = true
        echo port = 49522
        echo.
        echo [writer]
        echo enabled = true
        echo port = 49520
        echo.
        echo [memory]
        echo dirs = ["记忆/全局", "记忆/编程", "记忆/写作", "记忆/QQ Bot", "记忆/游戏开发"]
        echo.
        echo [domains]
        echo default = "全局"
        echo.
        echo [paths]
        echo logs_dir = "%%USERPROFILE%%\\.second-brain\\logs"
        echo session_file = "%%USERPROFILE%%\\.second-brain\\.current_session"
    )
    echo [OK] Config written.
)

echo.
echo =====================================================
echo  Setup complete!
echo =====================================================
echo.
echo  Next steps:
echo    1. Set the environment variable SECOND_BRAIN_CONFIG to:
echo       %CONFIG_FILE%
echo    2. Or copy the config to %%USERPROFILE%%\\.second-brain\\config.toml
echo    3. Start the daemons:
echo       python "%SCRIPT_DIR%src\obsidian_writer.py"
echo       python "%SCRIPT_DIR%src\supervisor.py"
echo    4. Restart Obsidian (if community plugins need the new folders)
echo.
pause
