#!/usr/bin/env bash
# =============================================================================
#  Second Brain Kit — macOS / Linux Setup Script
# =============================================================================
#  This script:
#    1. Checks Python availability
#    2. Asks for Obsidian vault path
#    3. Copies vault-template to the vault
#    4. Installs Python dependencies
#    5. Generates config.toml
#    6. Prints post-install instructions
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "====================================================="
echo "  Second Brain Kit — macOS / Linux Setup"
echo "====================================================="
echo ""

# ---- Check Python ----
if ! command -v python3 &>/dev/null; then
    echo "[ERROR] Python 3 is not installed or not in PATH."
    echo "        Please install Python 3.11+ from https://python.org"
    exit 1
fi

PYTHON="python3"

# ---- Get vault path ----
read -rp "Enter the full path to your Obsidian vault (e.g., /Users/me/my-vault): " VAULT_PATH

if [ -z "$VAULT_PATH" ]; then
    echo "[ERROR] Vault path cannot be empty."
    exit 1
fi

# Expand tilde if present
VAULT_PATH="${VAULT_PATH/#\~/$HOME}"

if [ ! -d "$VAULT_PATH" ]; then
    echo "[ERROR] Path does not exist: $VAULT_PATH"
    echo "        Please verify the path and re-run."
    exit 1
fi

echo "[OK] Vault found at: $VAULT_PATH"
echo ""

# ---- Install Python dependencies ----
echo "[*] Installing Python dependencies..."
$PYTHON -m pip install portalocker --quiet

# ---- Copy vault-template ----
echo "[*] Copying vault-template to your vault..."
cp -r "$SCRIPT_DIR/vault-template/"* "$VAULT_PATH/"
echo "[OK] Template files copied."

# ---- Generate config.toml ----
CONFIG_DIR="$HOME/.second-brain"
CONFIG_FILE="$CONFIG_DIR/config.toml"

if [ -f "$CONFIG_FILE" ]; then
    echo "[*] Config already exists at $CONFIG_FILE"
    echo "    Run again with --force to overwrite."
else
    mkdir -p "$CONFIG_DIR"
    echo "[*] Writing config to $CONFIG_FILE..."

    cat > "$CONFIG_FILE" <<TOML
# Second Brain Kit — generated by setup.sh

[vault]
path = "$VAULT_PATH"

[supervisor]
enabled = true
port = 49522

[writer]
enabled = true
port = 49520

[memory]
dirs = ["记忆/全局", "记忆/编程", "记忆/写作", "记忆/QQ Bot", "记忆/游戏开发"]

[domains]
default = "全局"

[paths]
logs_dir = "$HOME/.second-brain/logs"
session_file = "$HOME/.second-brain/.current_session"
TOML
    echo "[OK] Config written."
fi

echo ""
echo "====================================================="
echo "  Setup complete!"
echo "====================================================="
echo ""
echo "  Next steps:"
echo "    1. Set the environment variable:"
echo "       export SECOND_BRAIN_CONFIG=$CONFIG_FILE"
echo "       (add to your ~/.bashrc or ~/.zshrc)"
echo "    2. Start the daemons:"
echo "       $PYTHON \"$SCRIPT_DIR/src/obsidian_writer.py\" &"
echo "       $PYTHON \"$SCRIPT_DIR/src/supervisor.py\" &"
echo "    3. Restart Obsidian if needed."
echo ""
